import os
import subprocess
from subprocess import STDOUT,PIPE
import time
from py4j.java_gateway import JavaGateway


def run_simulation(deck_name, game_count):
    # Execute by specifying the classpath
    args = (["java", "-classpath", "/Users/russell/Documents/forge/forge-gui-desktop/target/classes:/Users/russell"
                                   "/Documents/forge/forge-core/target/classes:/Users/russell/.m2/repository/com/google"
                                   "/guava/guava/31.1-android/guava-31.1-android.jar:/Users/russell/.m2/repository/com"
                                   "/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar:/Users/russell/.m2"
                                   "/repository/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with"
                                   "-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar:/Users/russell"
                                   "/.m2/repository/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar:/Users/russell"
                                   "/.m2/repository/org/checkerframework/checker-qual/3.12.0/checker-qual-3.12.0.jar"
                                   ":/Users/russell/.m2/repository/com/google/errorprone/error_prone_annotations/2.11.0"
                                   "/error_prone_annotations-2.11.0.jar:/Users/russell/.m2/repository/com/google/j2objc"
                                   "/j2objc-annotations/1.3/j2objc-annotations-1.3.jar:/Users/russell/.m2/repository/org"
                                   "/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar:/Users/russell"
                                   "/Documents/forge/forge-game/target/classes:/Users/russell/.m2/repository/com"
                                   "/googlecode/minlog/1.2/minlog-1.2.jar:/Users/russell/.m2/repository/io/sentry/sentry"
                                   "-logback/5.7.0/sentry-logback-5.7.0.jar:/Users/russell/.m2/repository/io/sentry"
                                   "/sentry/5.7.0/sentry-5.7.0.jar:/Users/russell/.m2/repository/com/google/code/gson"
                                   "/gson/2.8.5/gson-2.8.5.jar:/Users/russell/.m2/repository/ch/qos/logback/logback"
                                   "-classic/1.2.11/logback-classic-1.2.11.jar:/Users/russell/.m2/repository/ch/qos"
                                   "/logback/logback-core/1.2.11/logback-core-1.2.11.jar:/Users/russell/.m2/repository"
                                   "/org/slf4j/slf4j-api/1.7.32/slf4j-api-1.7.32.jar:/Users/russell/Documents/forge/forge"
                                   "-ai/target/classes:/Users/russell/.m2/repository/org/apache/commons/commons-math3/3.6"
                                   ".1/commons-math3-3.6.1.jar:/Users/russell/Documents/forge/forge-gui/target/classes"
                                   ":/Users/russell/.m2/repository/com/thoughtworks/xstream/xstream/1.4.19/xstream-1.4.19"
                                   ".jar:/Users/russell/.m2/repository/io/github/x-stream/mxparser/1.2.2/mxparser-1.2.2"
                                   ".jar:/Users/russell/.m2/repository/xmlpull/xmlpull/1.1.3.1/xmlpull-1.1.3.1.jar:/Users"
                                   "/russell/.m2/repository/io/netty/netty-all/4.1.71.Final/netty-all-4.1.71.Final.jar"
                                   ":/Users/russell/.m2/repository/io/netty/netty-buffer/4.1.71.Final/netty-buffer-4.1.71"
                                   ".Final.jar:/Users/russell/.m2/repository/io/netty/netty-codec/4.1.71.Final/netty"
                                   "-codec-4.1.71.Final.jar:/Users/russell/.m2/repository/io/netty/netty-codec-dns/4.1.71"
                                   ".Final/netty-codec-dns-4.1.71.Final.jar:/Users/russell/.m2/repository/io/netty/netty"
                                   "-codec-haproxy/4.1.71.Final/netty-codec-haproxy-4.1.71.Final.jar:/Users/russell/.m2"
                                   "/repository/io/netty/netty-codec-http/4.1.71.Final/netty-codec-http-4.1.71.Final.jar"
                                   ":/Users/russell/.m2/repository/io/netty/netty-codec-http2/4.1.71.Final/netty-codec"
                                   "-http2-4.1.71.Final.jar:/Users/russell/.m2/repository/io/netty/netty-codec-memcache/4"
                                   ".1.71.Final/netty-codec-memcache-4.1.71.Final.jar:/Users/russell/.m2/repository/io"
                                   "/netty/netty-codec-mqtt/4.1.71.Final/netty-codec-mqtt-4.1.71.Final.jar:/Users/russell"
                                   "/.m2/repository/io/netty/netty-codec-redis/4.1.71.Final/netty-codec-redis-4.1.71"
                                   ".Final.jar:/Users/russell/.m2/repository/io/netty/netty-codec-smtp/4.1.71.Final/netty"
                                   "-codec-smtp-4.1.71.Final.jar:/Users/russell/.m2/repository/io/netty/netty-codec-socks"
                                   "/4.1.71.Final/netty-codec-socks-4.1.71.Final.jar:/Users/russell/.m2/repository/io"
                                   "/netty/netty-codec-stomp/4.1.71.Final/netty-codec-stomp-4.1.71.Final.jar:/Users"
                                   "/russell/.m2/repository/io/netty/netty-codec-xml/4.1.71.Final/netty-codec-xml-4.1.71"
                                   ".Final.jar:/Users/russell/.m2/repository/io/netty/netty-common/4.1.71.Final/netty"
                                   "-common-4.1.71.Final.jar:/Users/russell/.m2/repository/io/netty/netty-handler/4.1.71"
                                   ".Final/netty-handler-4.1.71.Final.jar:/Users/russell/.m2/repository/io/netty/netty"
                                   "-tcnative-classes/2.0.46.Final/netty-tcnative-classes-2.0.46.Final.jar:/Users/russell"
                                   "/.m2/repository/io/netty/netty-handler-proxy/4.1.71.Final/netty-handler-proxy-4.1.71"
                                   ".Final.jar:/Users/russell/.m2/repository/io/netty/netty-resolver/4.1.71.Final/netty"
                                   "-resolver-4.1.71.Final.jar:/Users/russell/.m2/repository/io/netty/netty-resolver-dns"
                                   "/4.1.71.Final/netty-resolver-dns-4.1.71.Final.jar:/Users/russell/.m2/repository/io"
                                   "/netty/netty-transport/4.1.71.Final/netty-transport-4.1.71.Final.jar:/Users/russell"
                                   "/.m2/repository/io/netty/netty-transport-rxtx/4.1.71.Final/netty-transport-rxtx-4.1"
                                   ".71.Final.jar:/Users/russell/.m2/repository/io/netty/netty-transport-sctp/4.1.71"
                                   ".Final/netty-transport-sctp-4.1.71.Final.jar:/Users/russell/.m2/repository/io/netty"
                                   "/netty-transport-udt/4.1.71.Final/netty-transport-udt-4.1.71.Final.jar:/Users/russell"
                                   "/.m2/repository/io/netty/netty-transport-classes-epoll/4.1.71.Final/netty-transport"
                                   "-classes-epoll-4.1.71.Final.jar:/Users/russell/.m2/repository/io/netty/netty"
                                   "-transport-native-unix-common/4.1.71.Final/netty-transport-native-unix-common-4.1.71"
                                   ".Final.jar:/Users/russell/.m2/repository/io/netty/netty-transport-classes-kqueue/4.1"
                                   ".71.Final/netty-transport-classes-kqueue-4.1.71.Final.jar:/Users/russell/.m2"
                                   "/repository/io/netty/netty-resolver-dns-classes-macos/4.1.71.Final/netty-resolver-dns"
                                   "-classes-macos-4.1.71.Final.jar:/Users/russell/.m2/repository/io/netty/netty"
                                   "-transport-native-epoll/4.1.71.Final/netty-transport-native-epoll-4.1.71.Final-linux"
                                   "-x86_64.jar:/Users/russell/.m2/repository/io/netty/netty-transport-native-epoll/4.1"
                                   ".71.Final/netty-transport-native-epoll-4.1.71.Final-linux-aarch_64.jar:/Users/russell"
                                   "/.m2/repository/io/netty/netty-transport-native-kqueue/4.1.71.Final/netty-transport"
                                   "-native-kqueue-4.1.71.Final-osx-x86_64.jar:/Users/russell/.m2/repository/io/netty"
                                   "/netty-transport-native-kqueue/4.1.71.Final/netty-transport-native-kqueue-4.1.71"
                                   ".Final-osx-aarch_64.jar:/Users/russell/.m2/repository/io/netty/netty-resolver-dns"
                                   "-native-macos/4.1.71.Final/netty-resolver-dns-native-macos-4.1.71.Final-osx-x86_64"
                                   ".jar:/Users/russell/.m2/repository/io/netty/netty-resolver-dns-native-macos/4.1.71"
                                   ".Final/netty-resolver-dns-native-macos-4.1.71.Final-osx-aarch_64.jar:/Users/russell"
                                   "/.m2/repository/org/fourthline/cling/cling-support/2.1.2/cling-support-2.1.2.jar"
                                   ":/Users/russell/.m2/repository/org/fourthline/cling/cling-core/2.1.2/cling-core-2.1.2"
                                   ".jar:/Users/russell/.m2/repository/org/seamless/seamless-util/1.1.2/seamless-util-1.1"
                                   ".2.jar:/Users/russell/.m2/repository/org/seamless/seamless-http/1.1.2/seamless-http-1"
                                   ".1.2.jar:/Users/russell/.m2/repository/org/seamless/seamless-xml/1.1.2/seamless-xml-1"
                                   ".1.2.jar:/Users/russell/.m2/repository/org/seamless/seamless-swing/1.1.2/seamless"
                                   "-swing-1.1.2.jar:/Users/russell/.m2/repository/org/lz4/lz4-java/1.8.0/lz4-java-1.8.0"
                                   ".jar:/Users/russell/.m2/repository/com/github/raeleus/TenPatch/tenpatch/5.2.2"
                                   "/tenpatch-5.2.2.jar:/Users/russell/.m2/repository/com/badlogicgames/gdx/gdx/1.9.9/gdx"
                                   "-1.9.9.jar:/Users/russell/.m2/repository/com/miglayout/miglayout-swing/4.2/miglayout"
                                   "-swing-4.2.jar:/Users/russell/.m2/repository/com/miglayout/miglayout-core/4.2"
                                   "/miglayout-core-4.2.jar:/Users/russell/.m2/repository/com/mortennobel/java-image"
                                   "-scaling/0.8.5/java-image-scaling-0.8.5.jar:/Users/russell/.m2/repository/com/jhlabs"
                                   "/filters/2.0.235/filters-2.0.235.jar:/Users/russell/.m2/repository/org/powermock"
                                   "/powermock-module-testng-common/2.0.9/powermock-module-testng-common-2.0.9.jar:/Users"
                                   "/russell/.m2/repository/org/powermock/powermock-reflect/2.0.9/powermock-reflect-2.0.9"
                                   ".jar:/Users/russell/.m2/repository/net/bytebuddy/byte-buddy/1.12.3/byte-buddy-1.12.3"
                                   ".jar:/Users/russell/.m2/repository/org/freemarker/freemarker/2.3.31/freemarker-2.3.31"
                                   ".jar:/Users/russell/.m2/repository/com/googlecode/soundlibs/jlayer/1.0.1-1/jlayer-1.0"
                                   ".1-1.jar:/Users/russell/.m2/repository/junit/junit/3.8.2/junit-3.8.2.jar:/Users"
                                   "/russell/.m2/repository/com/beust/jcommander/1.78/jcommander-1.78.jar:/Users/russell"
                                   "/.m2/repository/com/sipgate/mp3-wav/1.0.3/mp3-wav-1.0.3.jar:/Users/russell/.m2"
                                   "/repository/javazoom/jlayer/1.0.1/jlayer-1.0.1.jar:/Users/russell/.m2/repository/com"
                                   "/googlecode/soundlibs/mp3spi/1.9.5-1/mp3spi-1.9.5-1.jar:/Users/russell/.m2/repository"
                                   "/com/googlecode/soundlibs/tritonus-share/0.3.7-1/tritonus-share-0.3.7-1.jar:/Users"
                                   "/russell/.m2/repository/com/twelvemonkeys/imageio/imageio-jpeg/3.7.0/imageio-jpeg-3.7"
                                   ".0.jar:/Users/russell/.m2/repository/com/twelvemonkeys/imageio/imageio-core/3.7.0"
                                   "/imageio-core-3.7.0.jar:/Users/russell/.m2/repository/com/twelvemonkeys/imageio"
                                   "/imageio-metadata/3.7.0/imageio-metadata-3.7.0.jar:/Users/russell/.m2/repository/com"
                                   "/twelvemonkeys/common/common-lang/3.7.0/common-lang-3.7.0.jar:/Users/russell/.m2"
                                   "/repository/com/twelvemonkeys/common/common-io/3.7.0/common-io-3.7.0.jar:/Users"
                                   "/russell/.m2/repository/com/twelvemonkeys/common/common-image/3.7.0/common-image-3.7"
                                   ".0.jar", "forge.view.Main", "sim", "-n", str(game_count), "-q", "-d",
             deck_name, "AllLands.dck", "AllLands.dck", "AllLands.dck", "-Xms768m",
             "-XX:+UseParallelGC", "-Dsun.java2d.xrender=false"])
    os.chdir("/Users/russell/Documents/forge/forge-gui-desktop")
    p = subprocess.Popen(args, stdin=PIPE, stdout=PIPE, stderr=STDOUT)
    # Prevent processing from going down before starting the server
    stdout, stderr = p.communicate()
    print('This was "' + str(stdout) + '"')
    return str(stdout.decode())